#!/bin/sh
#
# (c) ben, untar.org
#

PROG='untar'
TITEL='a generic file extracter.'
DESC='Extracts files based on their ending (.zip, .tar.gz, ...)'
ARGS='[-h|--help] <file>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $PROG - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

if [ -f $1 ] ; then
case $1 in
  *.tar.bz2)   tar xvjf $1        ;;
  *.tar.gz)    tar xvzf $1     ;;
  *.bz2)       bunzip2 $1       ;;
  *.rar)       rar x $1     ;;
  *.gz)        gunzip $1     ;;
  *.tar)       tar xf $1        ;;
  *.tbz2)      tar xjf $1      ;;
  *.tgz)       tar xzf $1       ;;
  *.zip)       unzip $1     ;;
  *.Z)         uncompress $1  ;;
  *.7z)        7z x $1    ;;
  *)           echo "'$1' cannot be extracted via extract()" ;;
esac
else
    echo "'$1' is not a valid file"
fi
